In [2]:
import pandas as pd
import matplotlib as plt
import numpy as np
import re
import statistics

In [12]:
df = pd.read_csv("Data_mypham_Tpcn.csv")
df.head(60)

,Product Name,Category,Dosage Form,Price,Trademark,Brand Origin,Country,Rating
0,Viên uống Golex Ocavill hỗ trợ chống lại sự ph...,"Thận, tiền liệt tuyến",Viên nén,495000.0,OCAVILL,Anh,Anh,5.0
1,"Siro Bổ Phế Lábebé 120ml hỗ trợ bổ phế, giảm h...","Tăng sức đề kháng, miễn dịch",Siro,75000.0,NaN,Việt Nam,Việt Nam,5.0
2,Siro ống uống Canxi-D3-K2 5ml Kingphar bổ sung...,Bổ sung Canxi & Vitamin D,Hỗn dịch,105000.0,Kingphar,Việt Nam,Việt Nam,5.0
3,Siro Brauer Baby Kids D3+k2 High Potency MK-7 ...,Vitamin & Khoáng chất,Dung dịch uống,396000.0,Brauer,Úc,Úc,5.0
4,Thực phẩm bảo vệ sức khỏe KID GROW Kenko tăng ...,Cải thiện tăng cường chức năng,Siro,480000.0,KENKO,Nhật Bản,Nhật Bản,5.0
5,Thực phẩm bảo vệ sức khỏe OMEGA 3 PLUS Kenko h...,Cải thiện tăng cường chức năng,Viên nang mềm,920000.0,KENKO,Nhật Bản,Nhật Bản,4.5
6,Viên uống Omexxel Ginkgo 120 Premium Omexxel h...,Bổ não - cải thiện trí nhớ,Viên nang cứng,788000.0,OMEXXEL,Hoa Kỳ,Hoa Kỳ,5.0
7,Viên uống SkillMax Ocavill hỗ trợ tăng cường t...,"Bổ mắt, bảo vệ mắt",Viên nang mềm,670000.0,OCAVILL,NaN,Bulgaria,NaN
8,Viên uống Pikolin Ocavill hỗ trợ tăng tuần hoà...,Tuần hoàn máu,Viên nang mềm,492000.0,OCAVILL,NaN,Bulgaria,5.0
9,Viên nhai Borne Mineral New Nordic hỗ trợ phát...,Cơ xương khớp,Viên nén nhai,635000.0,NEW NORDIC,Thụy Điển,Thụy Điển,5.0
10,Thực phẩm bảo vệ sức khỏe Calcium Premium Jpan...,Cơ xương khớp,Viên nang cứng,920000.0,Jpanwell,Nhật Bản,Nhật Bản,5.0
11,"Viên uống Rama Bổ Phổi hỗ trợ bổ phổi, giảm ho...","Hô hấp, ho, xoang",Viên nén,132000.0,HGSG PHARMA,Việt Nam,Việt Nam,5.0
12,Viên uống hỗ trợ phụ nữ mang thai và phụ nữ ch...,Vitamin & Khoáng chất,Viên nang mềm,550000.0,Brauer,Úc,Úc,5.0
13,Viên sủi Kudos Kids Multivitamins Plus Calcium...,Vitamin & Khoáng chất,Viên sủi,116800.0,KUDOS,Singapore,Đức,5.0
14,Viên sủi Kudos Daily Vitamins Plus Biotin & Gi...,Vitamin & Khoáng chất,Viên sủi,101200.0,KUDOS,Singapore,Đức,5.0
15,Viên sủi Kudos Vitamin C 1000mg hương chanh gi...,Vitamin & Khoáng chất,Viên sủi,90400.0,KUDOS,Singapore,Đức,5.0
16,Siro Immune Defence Probiotic Liquid Brauer gi...,"Tăng sức đề kháng, miễn dịch",Siro,550000.0,Brauer,Úc,Úc,5.0
17,"Viên sủi Kudos Bone hương cam bổ sung canxi, v...",Vitamin & Khoáng chất,Viên sủi,90400.0,KUDOS,Singapore,Đức,5.0
18,Viên uống Ericllux Ocavill hỗ trợ tăng tiết dị...,Cơ xương khớp,Viên nén bao phim,650000.0,OCAVILL,NaN,Ý,5.0
19,"Viên uống BIO Hair, Nail and Skin Royal Care h...",Hỗ trợ làm đẹp,Viên nang,128000.0,Royal Care,Việt Nam,Việt Nam,5.0
20,Viên uống Natto Gold 3000FU Royal Care hỗ trợ ...,Thần kinh não,Viên nang cứng,295000.0,Royal Care,Việt Nam,Việt Nam,5.0
21,Viên uống Calci K-2 Pharma World hỗ trợ giảm n...,Bổ sung Canxi & Vitamin D,Viên nén,470000.0,Pharma World,Mỹ,Hoa Kỳ,5.0
22,Viên uống Omexxel Ginkgo 120 OMEXXEL hỗ trợ tă...,Thần kinh não,Viên nang mềm,688000.0,OMEXXEL,Hoa Kỳ,Hoa Kỳ,5.0
23,Nước giải rượu bia Ladodetox Nosamin Ladophar ...,"Giải rượu, cai rượu",Dung dịch uống,312000.0,Ladophar,Việt Nam,Việt Nam,5.0
24,Bào tử lợi khuẩn Livespo DIA 30 hỗ trợ giảm cá...,Vi sinh - Probiotic,Dung dịch uống,270000.0,Livespo,Việt Nam,Việt Nam,5.0
25,Viên uống Kaki Ekisu Tohchukasou Kenkan hỗ trợ...,Sinh lý nam,Viên nang mềm,515000.0,KenKan,Nhật Bản,Nhật Bản,4.8
26,Viên uống Calci Nano Hải Thượng Vương bổ sung ...,Cơ xương khớp,Viên nang cứng,347000.0,Hải Thượng Vương,Việt Nam,Việt Nam,5.0
27,Viên uống Triple Strength Glucosamine 1500mg P...,Cơ xương khớp,Viên nén,236800.0,Pharmekal,Hoa Kỳ,Hoa Kỳ,5.0
28,Dung dịch Bảo Dạ Phương Y Nam hỗ trợ giảm acid...,"Dạ dày, tá tràng",Dung dịch,115000.0,Phương Y Nam,Việt Nam,Việt Nam,5.0
29,Viên uống Milk Thistle Pharma World hỗ trợ chố...,Chức năng gan,Viên nang,445000.0,Pharma World,Mỹ,Hoa Kỳ,NaN
30,Bột hòa tan Soki Deli cải thiện tình trạng biế...,Hỗ trợ trao đổi chất,Dạng bột,360000.0,Soki,Việt Nam,Việt Nam,5.0
31,Dung dịch Feginic bổ sung sắt cho người thiếu ...,Bổ sung Sắt & Axit Folic,Dung dịch,108000.0,GINIC,Việt Nam,Việt Nam,4.9
32,Siro Ginkid GINIC thanh nhiệt mát gan (4 vỉ x ...,Chức năng gan,Dung dịch,92000.0,NaN,Việt Nam,Việt Nam,5.0
33,"Siro Ginkid GINIC nhuận tràng, bổ sung chất xơ...",Táo bón,Siro,100000.0,NaN,Việt Nam,Việt Nam,5.0
34,"Siro Ginkid ZinC bổ sung kẽm, hỗ trợ tăng sức ...","Tăng sức đề kháng, miễn dịch",Siro,89000.0,NaN,Việt Nam,Việt Nam,5.0
35,"Siro Ginkid Ho Cam NEW 80ml hỗ trợ bổ phế, giả...","Hô hấp, ho, xoang",Siro,59000.0,NaN,Việt Nam,Việt Nam,5.0
36,"Dung dịch LiveSpo Clausy bổ sung lợi khuẩn, gi...",Vi sinh - Probiotic,Dung dịch,159000.0,Livespo,Việt Nam,Việt Nam,5.0
37,Viên uống Si-Liver Naga Vesta giúp tăng cường ...,Chức năng gan,Viên nang,225000.0,Vesta,Việt Nam,Việt Nam,5.0
38,Viên uống Multivitamin +Zn +D3 Royal Care hỗ t...,Vitamin tổng hợp,Viên nang cứng,175000.0,Royal Care,Việt Nam,Việt Nam,4.9
39,Viên uống JP Lady Jpanwell cung cấp vitamin hỗ...,Hỗ trợ mãn kinh,Viên nang,1300000.0,Jpanwell,Nhật Bản,Nhật Bản,5.0
40,Viên uống Lung Care+ Jpanwell hỗ trợ hệ hô hấp...,"Hô hấp, ho, xoang",Viên nang,995000.0,Jpanwell,Nhật Bản,Nhật Bản,5.0
41,Viên uống LéAna Ocavill hỗ trợ cân bằng nội ti...,Cân bằng nội tiết tố,Viên nang mềm,544000.0,OCAVILL,Bulgaria,Bulgaria,4.9
42,Viên uống Dr. Caci Ocavill giúp xương và răng ...,Vitamin tổng hợp,Viên nang cứng,570000.0,OCAVILL,Bulgaria,Pháp,4.9
43,Xịt họng Xuyên Tâm Liên Hải Thượng Vương hỗ tr...,"Hô hấp, ho, xoang",Dung dịch,84800.0,Hải Thượng Vương,Việt Nam,Việt Nam,5.0
44,"Xịt họng Propolis Ivy Royal Care giảm ho, đờm,...","Hô hấp, ho, xoang",Dung dịch,77000.0,Royal Care,Việt Nam,Việt Nam,5.0
45,Viên sủi Optimax Immunity Booster Vid-Fighter ...,"Tăng sức đề kháng, miễn dịch",Viên sủi,118000.0,Optimax,Hoa Kỳ,Hoa Kỳ,4.9
46,Bột Nước Mát Herbal Drink Powder Datino thanh ...,Chức năng gan,NaN,33600.0,Datino,Việt Nam,Việt Nam,5.0
47,"Siro Datadu Kingphar hỗ trợ hạn chế đau đầu, s...","Hô hấp, ho, xoang",Siro,82000.0,Kingphar,Việt Nam,Việt Nam,5.0
48,"Siro Nopanho Kingphar giúp bổ phố, hạn chế ho ...","Hô hấp, ho, xoang",Siro,37000.0,Kingphar,Việt Nam,Việt Nam,5.0
49,Viên uống Bifido Plus Jpanwell bổ sung các lợi...,Đại tràng,Viên nang,990000.0,Jpanwell,Nhật Bản,Nhật Bản,5.0
50,"Cốm lợi sữa TT.Galac Traphaco hỗ trợ lợi sữa, ...",Cải thiện tăng cường chức năng,Cốm,128000.0,Traphaco,Việt Nam,Việt Nam,5.0
51,Viên uống Bye Tree Royal Care hỗ trợ tăng sức ...,Hỗ trợ điều trị trĩ,Viên nang,200000.0,Royal Care,Việt Nam,Việt Nam,5.0
52,Viên uống Tố Nữ Vương Royal Care hỗ trợ cải th...,Sinh lý nữ,Viên nang cứng,116000.0,Royal Care,Việt Nam,Việt Nam,4.9
53,Viên uống B Complex Vitamin Royal Care hỗ trợ ...,Vitamin tổng hợp,Viên nang cứng,160000.0,Royal Care,Việt Nam,Việt Nam,4.9
54,Viên uống Hato Gold Jpanwell cải thiện tim mạc...,Sức khoẻ tim mạch,Viên nang,995000.0,Jpanwell,Nhật Bản,Nhật Bản,5.0
55,Viên uống hỗ trợ dạ dày Dr.Sto Jpanwell (60 viên),"Dạ dày, tá tràng",Viên nang,792000.0,Jpanwell,Nhật Bản,Nhật Bản,4.8
56,Viên bổ thận Kidney Plus Jpanwell hỗ trợ bổ th...,"Thận, tiền liệt tuyến",Viên nang,990000.0,Jpanwell,Nhật Bản,Nhật Bản,5.0
57,"Viên uống Dr. Liver Jpanwell bổ gan, tăng cườn...",Chức năng gan,Viên nang,990000.0,Jpanwell,Nhật Bản,Nhật Bản,4.8
58,Viên uống Glucosamine And Chondroitin Jpanwell...,Cơ xương khớp,Viên nang,960000.0,Jpanwell,Nhật Bản,Nhật Bản,5.0
59,Viên uống Gaba Jpanwell giảm các triệu chứng m...,Hỗ trợ giấc ngủ ngon,Viên nang,960000.0,Jpanwell,Nhật Bản,Nhật Bản,5.0

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1485 entries, 0 to 1484
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product Name  1485 non-null   object
 1   Category      1485 non-null   object
 2   Dosage Form   1101 non-null   object
 3   Price         1485 non-null   float64
 4   Trademark     1376 non-null   object
 5   Brand Origin  1427 non-null   object
 6   Country       1481 non-null   object
 7   Rating        1024 non-null   float64
dtypes: float64(2), object(6)
memory usage: 92.9+ KB

In [14]:
for col in df.columns:
    print(type(df[col][0]))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.float64'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.float64'>

In [15]:
cate = []
for val in df['Category']:
    cate.append(re.split(', | &', val))
    
df['Chuc nang'] = cate
df.head()

,Product Name,Category,Dosage Form,Price,Trademark,Brand Origin,Country,Rating,Chuc nang
0,Viên uống Golex Ocavill hỗ trợ chống lại sự ph...,"Thận, tiền liệt tuyến",Viên nén,495000.0,OCAVILL,Anh,Anh,5.0,"[Thận, tiền liệt tuyến]"
1,"Siro Bổ Phế Lábebé 120ml hỗ trợ bổ phế, giảm h...","Tăng sức đề kháng, miễn dịch",Siro,75000.0,NaN,Việt Nam,Việt Nam,5.0,"[Tăng sức đề kháng, miễn dịch]"
2,Siro ống uống Canxi-D3-K2 5ml Kingphar bổ sung...,Bổ sung Canxi & Vitamin D,Hỗn dịch,105000.0,Kingphar,Việt Nam,Việt Nam,5.0,"[Bổ sung Canxi, Vitamin D]"
3,Siro Brauer Baby Kids D3+k2 High Potency MK-7 ...,Vitamin & Khoáng chất,Dung dịch uống,396000.0,Brauer,Úc,Úc,5.0,"[Vitamin, Khoáng chất]"
4,Thực phẩm bảo vệ sức khỏe KID GROW Kenko tăng ...,Cải thiện tăng cường chức năng,Siro,480000.0,KENKO,Nhật Bản,Nhật Bản,5.0,[Cải thiện tăng cường chức năng]

In [16]:
del df['Category']

In [17]:
df

,Product Name,Dosage Form,Price,Trademark,Brand Origin,Country,Rating,Chuc nang
0,Viên uống Golex Ocavill hỗ trợ chống lại sự ph...,Viên nén,495000.0,OCAVILL,Anh,Anh,5.0,"[Thận, tiền liệt tuyến]"
1,"Siro Bổ Phế Lábebé 120ml hỗ trợ bổ phế, giảm h...",Siro,75000.0,NaN,Việt Nam,Việt Nam,5.0,"[Tăng sức đề kháng, miễn dịch]"
2,Siro ống uống Canxi-D3-K2 5ml Kingphar bổ sung...,Hỗn dịch,105000.0,Kingphar,Việt Nam,Việt Nam,5.0,"[Bổ sung Canxi, Vitamin D]"
3,Siro Brauer Baby Kids D3+k2 High Potency MK-7 ...,Dung dịch uống,396000.0,Brauer,Úc,Úc,5.0,"[Vitamin, Khoáng chất]"
4,Thực phẩm bảo vệ sức khỏe KID GROW Kenko tăng ...,Siro,480000.0,KENKO,Nhật Bản,Nhật Bản,5.0,[Cải thiện tăng cường chức năng]
...,...,...,...,...,...,...,...,...
1480,Kem ngừa mụn ban đêm Canova Acnell Sifarma giú...,NaN,435000.0,Sifarma,Ý,Ý,5.0,[Chăm sóc da mặt]
1481,Kem dưỡng giảm đốm nâu Eucerin Even Skin Spotl...,NaN,670000.0,Eucerin,Đức,Bỉ,5.0,"[Kem trị nám, tàn nhang, đốm nâu]"
1482,Sữa rửa mặt dịu nhẹ sáng da Eucerin Spotless B...,NaN,519000.0,Eucerin,Đức,Thái Lan,NaN,"[Sữa rửa mặt (Kem, gel, sữa)]"
1483,Sữa dưỡng thể trắng da Eucerin Even Skin Spotl...,NaN,280000.0,Eucerin,Đức,Thái Lan,NaN,[Chăm sóc cơ thể]
1484,Kem dưỡng sáng da ban đêm Eucerin Even Skin Sp...,Dạng kem,929000.0,Eucerin,Đức,Ba Lan,NaN,"[Kem trị nám, tàn nhang, đốm nâu]"

In [9]:
df.drop_duplicates()

TypeError: unhashable type: 'list'